### ISSUE TITLE
This gem doesn't appear to exist

### ISSUE THREAD

**Issue by drkpxl** [mwynholds/southy#1]
$ gem install southy
ERROR:  Could not find a valid gem 'southy' (>= 0) in any repository
ERROR:  Possible alternatives: south, soauth, slushy, smithy, so_auth

Also looking on RubyGems.org gives the same result.
https://rubygems.org/search?utf8=%E2%9C%93&query=southy

**Comment by evliu** [comment]
+1

**Comment by huyhong** [comment]
You can build the gem locally and install it, works for me.
`bundle install`
`gem build southy.gemspec`
`gem install southy-1.1.gem`

**Comment by kbaegis** [comment]
Thanks!  Had the same problem.  Add to the README?

**Comment by tjs198** [comment]
can someone help, got same error as hubertron, tried to build gem locally like huyhong commented, but get this error: 
tjs-macbook-pro:~ tjsterba$ sudo gem install southy
Password:
ERROR:  Could not find a valid gem 'southy' (>= 0) in any repository
ERROR:  Possible alternatives: south, mouth, slushy, smithy, so_auth
tjs-macbook-pro:~ tjsterba$ install southy
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
tjs-macbook-pro:~ tjsterba$ southy
-bash: southy: command not found
tjs-macbook-pro:~ tjsterba$ %southy
-bash: fg: %southy: no such job
tjs-macbook-pro:~ tjsterba$ bundle install gem build southy.gemspec
-bash: bundle: command not found
tjs-macbook-pro:~ tjsterba$ cd southy
tjs-macbook-pro:southy tjsterba$ bundle install
-bash: bundle: command not found
tjs-macbook-pro:southy tjsterba$ gem build southy.gemspec
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  no homepage specified
WARNING:  description and summary are identical
WARNING:  open-ended dependency on json (>= 0) is not recommended
  if json is semantically versioned, use:
    add_runtime_dependency 'json', '~> 0'
WARNING:  open-ended dependency on tzinfo (>= 0) is not recommended
  if tzinfo is semantically versioned, use:
    add_runtime_dependency 'tzinfo', '~> 0'
WARNING:  open-ended dependency on slack-ruby-client (>= 0.14.1) is not recommended
  if slack-ruby-client is semantically versioned, use:
    add_runtime_dependency 'slack-ruby-client', '~> 0.14', '>= 0.14.1'
WARNING:  open-ended dependency on standalone_migrations (>= 0) is not recommended
  if standalone_migrations is semantically versioned, use:
    add_runtime_dependency 'standalone_migrations', '~> 0'
WARNING:  open-ended dependency on pg (>= 0) is not recommended
  if pg is semantically versioned, use:
    add_runtime_dependency 'pg', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on minitest (>= 0, development) is not recommended
  if minitest is semantically versioned, use:
    add_development_dependency 'minitest', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: southy
  Version: 2.0
  File: southy-2.0.gem
tjs-macbook-pro:southy tjsterba$ sudo gem install southy-2.0.gem
Building native extensions.  This could take a while...
ERROR:  Error installing southy-2.0.gem:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/pg-1.2.2/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20200123-2344-11o9e9q.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/pg-1.2.2 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/pg-1.2.2/gem_make.out
